In [1]:
import numpy as np

In [5]:
W = np.array([[1, 0, -1],[0, 1, -1],[-1, 0, -1],[0, -1, -1]])
W

array([[ 1,  0, -1],
       [ 0,  1, -1],
       [-1,  0, -1],
       [ 0, -1, -1]])

In [6]:
V = np.array([[1, 1, 1, 1, 0],[-1, -1, -1, -1, 2]])
V

array([[ 1,  1,  1,  1,  0],
       [-1, -1, -1, -1,  2]])

In [7]:
x = np.array([3, 14, 1])
x

array([ 3, 14,  1])

In [8]:
z = W @ x
z

array([  2,  13,  -4, -15])

In [15]:
f = lambda x: max(0, x)
vf = np.vectorize(f)

In [18]:
vf(z)

array([ 2, 13,  0,  0])

In [30]:
U = V @ np.hstack((vf(z),np.array([1])))
U

array([ 15, -13])

In [31]:
vf(U)

array([15,  0])

In [32]:
def softmax(x1, x2):
    return np.array([np.exp(x1)/(np.exp(x1)+np.exp(x2)), np.exp(x2)/(np.exp(x1)+np.exp(x2))])

In [33]:
softmax(vf(U)[0], vf(U)[1])

array([9.99999694e-01, 3.05902227e-07])